### ISSUE TITLE
Access to the aligned culture LLMs

### ISSUE THREAD

**Issue by jack-ai661** [Jiahao-Yuan/CulturalPalette#1]
Hey, thanks for the great work! Will you be open-sourcing the Culture LLMs? That would be really helpful! Or could you teach me how to quickly align them?

**Comment by Jiahao-Yuan** [comment]
Thank you for your interest! You can install ms-swift using the following command:
```bash
pip install 'ms-swift[llm]' -U
```
For quick alignment, please refer to the [official Swift documentation](https://swift.readthedocs.io/en/latest/).
Feel free to reach out if you need further help!
